---
title: "Credit spread and financial crisis"
author: "Arvind Krishnamurthy and Tyler Muir"
date: "September 2017 @ NBER"
output:
  html_document: 
    theme: paper
---


**The FZ-theory of crisis**

A sizable shock to a fragile financial sector results in a financial crisis 
with bank runs, credit crunch as well as output contraction.

- Measure of financial fragility ($\mathcal{F}$): growth in credit/GDP
- Measure of the shock ($\mathcal{Z}$): change in credit spread

Normalizing the spreads: dividing the credit spread by the average spread for 
that country: $s_{i,t}=Spread_{i,t}/\overline{Spread_i}$

### Crisis and aftermath

Insights from event study:

- Spreads are 20% below their average value in the years before crisis
- Credit grows faster than average than averages before crisis
- GDP grows slightly faster than average in the years before crisis

Credit spread and crisis intensity:

$$ 
\begin{aligned}
\ln\left(\frac{y_{i,t+k}}{y_{i,t}}\right) = \alpha_i + \lambda_t + 
  & \underset{-0.30(0.44)}{1_{i,t}^c\times b_1^c s_{i,t}} + 
    \underset{-7.46(1.46)}{1_{i,t}^c\times b_2^c \Delta s_{i,t}} + \\
  & \underset{-0.49(0.23)}{1_{i,t}^n\times b_1^n s_{i,t}} + 
    \underset{-0.52(0.35)}{1_{i,t}^n\times b_2^n \Delta s_{i,t}} + 
    c(L)x_{i,t} + \epsilon_{i,t+k} 
\end{aligned}
$$

- Changes in spreads ($\Delta s_{i,t}$) rather than the level of spreads 
  ($s_{i,t}$) explains GDP decline.
- Association between spread spike and declining output is a crisis-specific 
  result ($1_{i,t}^c$); no similar result found in non-crisis period 
  ($1_{i,t}^n$).
- Change in spreads explains output in crisis, but not recessions.

Crisis triggers and amplifiers:

$$ 
\ln\left(\frac{y_{i,t+k}}{y_{i,t}}\right) = \alpha_i + \lambda_t + 
    \underset{-2.52(0.76)}{\text{HighCredit}_{i,t}\times\Delta s_{i,t}} + 
    c(L)x_{i,t} + \epsilon_{i,t+k} 
$$

HighCredit counts the number of years (within a 5-year window) 
that annual credit growth has excced its full sample medium.

- Unconditional path of GDP following a spread spike: 1% lower
- Conditioned on HighCredit, GDP following a spread spike: 2.5% lower


**Pre-crisis Period**

Crisis are preceded by *frothy* credit-market conditions (high credit 
growth coupled with low risk perception).

Pre-crisis spread and credit growth:

$$ 
s_{i,t} = \alpha_i + \lambda_t + \underset{-0.34(0.15)}{1_{i,t-5,t-1}} + 
\underset{-1.42(0.78)}{1_{i,t-5,t-1}} \times \Delta Credit_{i,t-1} + 
1_{t+1, t+3} + c(L)x_{i,t} + \epsilon_{i,t} 
$$

$1_{t-5,t-1}$: if it is five years before a crisis; 
$1_{t+1, t+3}$: if it is three years after a crisis. 
Therefore, pre-crisis dummy is judged relative to other "normal times" 
rather relative to crisis times. 
Conclusion: Spreads are low ahead of a crisis despite the fact that credit 
growth is high before a crisis (frothy market condition).

Credit supply expansions predict crisis:

$$ 
\text{Prob}(1_{i,t}^c) = \alpha_i + \lambda_t + 
\underset{2.00(0.40)}{\text{HighFroth}_{i,t}\times\text{HighCredit}_{i,t}}
+ c(L)x_{i,t} + \epsilon_{i,t} 
$$

Froth is measured by the difference between the actual spreads and the spreads
predicted by GDP and credit growth.
HighFroth is the 5-year average of dummies that indicate Froth value is above 
the median.

- Episodes of low spreads and high credit growth are precursors to crisis.
- Froth raises the likelihood of a crisis but not a recession.
- The results are considerably weakened in out-of-sample regressions.


© Original paper: [download](https://www.nber.org/system/files/working_papers/w23850/w23850.pdf)